In [3]:
import pandas as pdty
import numpy as np
import xml_files as  #xmlfilestoidentifyfacesinvideo

ModuleNotFoundError: ignored

In [2]:
import cv2 #computervison

In [ ]:
import time #timetofphoto
import date #dateoftheday

In [ ]:
face_detect = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')
detect = xml_file_extraction_default_frontalface 'haarcascade.Capture'

In [ ]:
source = cv2.VideoCapture(0)
input_images = []
targets = []
count = 0
for i in range(2):
    no_of_images = 0
    input("Enter to start")
    while 1:
        _,image = source.read(0)
        gray = cv2.cvtColor(image,cv2.COLOR_BGR2GRAY)
        detected_faces = face_detect.detectMultiScale(gray, 1.2, 9)
        if len(detected_faces) > 1:
            continue
        for each_face in detected_faces:
            x, y, w, h = each_face
            cv2.rectangle(image,(x,y), (x+w, y+h),(0, 0, 255), 3)
            crop = gray[y:y+h, x:x+w]
            cropped_image = cv2.resize(crop,(100, 100))
            input_images.append(cropped_image)
            targets.append(count)

            no_of_images += 1
            cv2.putText(image, "image no : " + str(no_of_images), (x, y), cv2.FONT_HERSHEY_SIMPLEX, 1,(100,100,100), 2)

            cv2.imshow('major project', cropped_image)
            key = cv2.waitKey(1)
            cv2.imshow("face window", image)
        if no_of_images == 500:
               break

    count += 1

    cv2.destroyAllWindows()
source.release()

Enter to start1


error: ignored

In [ ]:
input_images

[array([[121, 120, 117, ..., 185, 191, 200],
        [119, 119, 118, ..., 183, 190, 200],
        [118, 119, 117, ..., 182, 188, 196],
        ...,
        [112, 112, 109, ..., 113, 110, 110],
        [109, 111, 107, ..., 112, 110, 111],
        [106, 109, 109, ..., 111, 110, 111]], dtype=uint8),
 array([[129, 127, 125, ..., 186, 193, 203],
        [130, 127, 123, ..., 182, 190, 198],
        [130, 125, 121, ..., 178, 187, 196],
        ...,
        [106, 100, 104, ...,  74,  70,  65],
        [105, 104, 109, ...,  74,  69,  64],
        [106, 107, 110, ...,  66,  64,  62]], dtype=uint8),
 array([[150, 147, 143, ..., 152, 151, 151],
        [146, 140, 136, ..., 150, 149, 148],
        [141, 134, 130, ..., 148, 148, 148],
        ...,
        [116, 117, 118, ..., 187, 187, 188],
        [115, 115, 117, ..., 187, 188, 188],
        [115, 115, 116, ..., 186, 187, 187]], dtype=uint8),
 array([[148, 146, 146, ..., 150, 152, 152],
        [147, 146, 145, ..., 148, 149, 151],
        [146, 14

In [ ]:
len(input_images)

1000

In [ ]:
len(targets)

1000

In [ ]:
input_images_normalized = np.array(input_images)/255.0
input_images_normalized

array([[[0.4745098 , 0.47058824, 0.45882353, ..., 0.7254902 ,
         0.74901961, 0.78431373],
        [0.46666667, 0.46666667, 0.4627451 , ..., 0.71764706,
         0.74509804, 0.78431373],
        [0.4627451 , 0.46666667, 0.45882353, ..., 0.71372549,
         0.7372549 , 0.76862745],
        ...,
        [0.43921569, 0.43921569, 0.42745098, ..., 0.44313725,
         0.43137255, 0.43137255],
        [0.42745098, 0.43529412, 0.41960784, ..., 0.43921569,
         0.43137255, 0.43529412],
        [0.41568627, 0.42745098, 0.42745098, ..., 0.43529412,
         0.43137255, 0.43529412]],

       [[0.50588235, 0.49803922, 0.49019608, ..., 0.72941176,
         0.75686275, 0.79607843],
        [0.50980392, 0.49803922, 0.48235294, ..., 0.71372549,
         0.74509804, 0.77647059],
        [0.50980392, 0.49019608, 0.4745098 , ..., 0.69803922,
         0.73333333, 0.76862745],
        ...,
        [0.41568627, 0.39215686, 0.40784314, ..., 0.29019608,
         0.2745098 , 0.25490196],
        [0.4

In [ ]:
input_images_normalized_reshaped = input_images_normalized.reshape(1000, 100, 100, 1)
input_images_normalized_reshaped

array([[[[0.4745098 ],
         [0.47058824],
         [0.45882353],
         ...,
         [0.7254902 ],
         [0.74901961],
         [0.78431373]],

        [[0.46666667],
         [0.46666667],
         [0.4627451 ],
         ...,
         [0.71764706],
         [0.74509804],
         [0.78431373]],

        [[0.4627451 ],
         [0.46666667],
         [0.45882353],
         ...,
         [0.71372549],
         [0.7372549 ],
         [0.76862745]],

        ...,

        [[0.43921569],
         [0.43921569],
         [0.42745098],
         ...,
         [0.44313725],
         [0.43137255],
         [0.43137255]],

        [[0.42745098],
         [0.43529412],
         [0.41960784],
         ...,
         [0.43921569],
         [0.43137255],
         [0.43529412]],

        [[0.41568627],
         [0.42745098],
         [0.42745098],
         ...,
         [0.43529412],
         [0.43137255],
         [0.43529412]]],


       [[[0.50588235],
         [0.49803922],
         [0.49

In [ ]:
from keras.utils import np_utils
targets = np_utils.to_categorical(targets)
targets

array([[1., 0.],
       [1., 0.],
       [1., 0.],
       ...,
       [0., 1.],
       [0., 1.],
       [0., 1.]], dtype=float32)

In [ ]:
targets[ : 100]

array([[1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(input_images_normalized_reshaped, targets)

In [ ]:
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((750, 100, 100, 1), (250, 100, 100, 1), (750, 2), (250, 2))

In [ ]:
from keras.models import Sequential
from keras.layers import Dense, Activation, Conv2D, MaxPooling2D, Dropout, Flatten
from tensorflow.keras.optimizers import SGD
from keras.callbacks import ModelCheckpoint

In [ ]:
model = Sequential()
model.add(Conv2D(300, (3,3),input_shape=(100, 100, 1)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Conv2D(100, (3,3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Dropout(0.3))
model.add(Flatten())

model.add(Dense(50, activation='relu'))
model.add(Dense(2, activation='softmax'))

model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [ ]:
cp = ModelCheckpoint('best_one', verbose=0, save_best_only=True)
model.fit(x_train, y_train, epochs = 3, callbacks=[cp], validation_split=0.2)

Epoch 1/3
19/19 [==============================] - ETA: 0s - loss: 0.7213 - accuracy: 0.5083WARNING:tensorflow:From C:\Users\user\anaconda3\envs\new_env\Lib\site-packages\tensorflow\python\training\tracking\tracking.py:111: Model.state_updates (from tensorflow.python.keras.engine.training) is deprecated and will be removed in a future version.
Instructions for updating:
This property should not be used in TensorFlow 2.0, as updates are applied automatically.
Instructions for updating:
This property should not be used in TensorFlow 2.0, as updates are applied automatically.
INFO:tensorflow:Assets written to: best_one\assets
19/19 [==============================] - 63s 3s/step - loss: 0.7213 - accuracy: 0.5083 - val_loss: 0.5922 - val_accuracy: 0.5000
Epoch 2/3
19/19 [==============================] - 62s 3s/step - loss: 0.3492 - accuracy: 0.8800 - val_loss: 0.0839 - val_accuracy: 0.9667
Epoch 3/3
19/19 [==============================] - 61s 3s/step - loss: 0.0582 - accuracy: 0.9800 - va

In [ ]:
from keras.models import load_model
model = load_model('best_one')

In [ ]:
import os
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email.mime.image import MIMEImage
from email import encoders

In [ ]:
source = cv2.VideoCapture(0)

while 1:
    _, image = source.read(0)
    #print("Captured image")
    gray = cv2.cvtColor(image,cv2.COLOR_BGR2GRAY)
    detected_faces = face_detect.detectMultiScale(gray, 1.2, 9)
    #print("Detected faces",len(detected_faces))
    if len(detected_faces) > 1:
        continue
    for each_face in detected_faces:
        # Each bbox is a rectangle representing
        # the bounding box around the detected object
        x, y, w, h = each_face
        cv2.rectangle(image, (x, y), (x+w, y+h), (0, 0, 255), 3)
        # Cropped object
        crop = gray[y:y+h, x:x+w]
        cropped_image = cv2.resize(crop, (100, 100))
        normalized_image = cropped_image/255
        reshaped_face = np.reshape(normalized_image, (1, 100, 100, 1))
        result = model.predict(reshaped_face)[0]
        if result[0] >  result[1]:
            cv2.rectangle(image, (x, y), (x + w, y + h), (0, 255, 0), 2)
            cv2.putText(image, "family member", (x, y), cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 255, 0), 2)


        if result[1] >  result[0]:
            cv2.rectangle(image, (x, y), (x + w, y + h), (0, 0, 255), 2)
            cv2.putText(image, "intruder", (x, y), cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 0, 255), 2)


            #these line of codes is for saving image captured by webcam
            sub_face = image[y:y+h, x:x+w]

            #this is the location where image is saved in .jpg extension
            FaceFileName = "C:\\Users\\user\\OneDrive\\Documents\\Verzeo Internship\\AI-MAJOR-MAY\\files\\captured faces" + str(y) + ".jpg"

            #time.sleep is used so that detected image is captured and saved after every 5 sec
            time.sleep(5)
            cv2.imwrite(FaceFileName, sub_face)

            #these codes are for emailing
            msg = MIMEMultipart()
            img_data = open(FaceFileName, 'rb').read()
            msg['Subject'] = 'There is an Intruder'
            msg['From'] = 'From-Mail-Id@gmail.com'
            msg['To'] = 'To-Mail-Id@gmail.com'

            message = "Someone Entered Your Room"
            msg.attach(MIMEText(message, 'plain'))
            img = MIMEImage(img_data, name=os.path.basename(FaceFileName))
            msg.attach(img)
            s = smtplib.SMTP_SSL('smtp.googlemail.com' , 465)
            s.ehlo()


            s.login(msg['From'] , 'password')
            s.sendmail(msg['From'], msg['To'], msg.as_string())







    cv2.imshow('Verzeo Project', image)
    key = cv2.waitKey(1)
    if key == 23:
        break
cv2.destroyAllWindows()
source.release()